### ISSUE TITLE
How to understand the running results？

### ISSUE THREAD

**Issue by ZhengyeHan** [Axelrod-Python/TourExec#11]
Running the code successfully shows the results shown in the figure：
![image](https://github.com/Axelrod-Python/TourExec/assets/111236370/38bd6014-e59c-42e9-bbee-616b669c64e8)

What do rowsc, colsc, aveRowsc, avecolsc, 2ndRndTFT, 2nDRNDTFT-col mean? How should I know which strategies to use to get the corresponding ranking? I can only see the ranking but not the strategy name.

@marcharper Thank you very much for your help last time. Would it be convenient for you to look at this problem again?

**Comment by marcharper** [comment]
The main point of this repository is just to host the source strategies. For analysis, running tournaments, etc. you want to use https://github.com/Axelrod-Python/axelrod-fortran and https://github.com/Axelrod-Python/Axelrod

**Comment by ZhengyeHan** [comment]
> The main point of this repository is just to host the source strategies. For analysis, running tournaments, etc. you want to use https://github.com/Axelrod-Python/axelrod-fortran and https://github.com/Axelrod-Python/Axelrod

Thank you for your reply.
In fact, I have already looked at both of the websites. Due to my recent scientific research needs, I want to attempt to reproduce either the results of the first tournament or the second tournament.

Before finding the current website, I initially came across this one: https://github.com/Axelrod-Python/Axelrod. In an attempt to reproduce the first Axelrod tournament, I ran the code from this website but found that I couldn’t replicate the results. Later, I read your documentation and realized that you also couldn’t reproduce it due to the unavailability of the source code.

Subsequently, I learned that the second tournament has Fortran source code. So, I found this website: https://github.com/Axelrod-Python/axelrod-fortran and tried to reproduce the second tournament’s source code. However, on this website, it is mentioned that to run the code here, one needs to first compile the Fortran source code. That’s why I ended up finding the current website here.
![image](https://github.com/Axelrod-Python/TourExec/assets/111236370/015a028e-11ff-4df5-800f-76195aa86203)

Please forgive my ignorance. My question is how to utilize the code from the following website to run the complete second tournament: [Axelrod-Python/axelrod-fortran](https://github.com/Axelrod-Python/axelrod-fortran). The examples you’ve provided demonstrate how to run a match between two strategies, but they don’t explain how to run a tournament involving all 63 strategies.

I also came across this video by Owen Campbell: [YouTube Video](https://www.youtube.com/watch?v=OSFCvv2wpOU). In the video, Owen Campbell showcases the differences between the results of the replicated tournament involving 63 strategies and the original paper’s results. I’m curious about how to achieve such results
![image](https://github.com/Axelrod-Python/TourExec/assets/111236370/e3ac60e2-54b5-476d-850d-ce539defbaab)

**Comment by marcharper** [comment]
@drvinceknight FYI

If you look at the example at https://github.com/Axelrod-Python/axelrod-fortran you can see that the fortran strategies can be loaded like other strategies in the axelrod library. So you just need to form a tournament using axelrod-python with the strategies for the second tournament and the same parameters (match lengths and so on). See [here](https://github.com/Axelrod-Python/revisiting-axelrod-second/blob/update-data-collection/src/run_original_tournament.py) for an example from a study we ran some time ago (but have not yet published in a journal).

However you should note that these are not the exact strategies from the second tournament. What we actually have is some testing code from around the same time and there appear to be some deviations from the published second tournament results (as seen in Owen's talk). Sufficiently complete descriptions of the strategies do not otherwise exist as far as we know to correct the strategies. (If you find something, please share!) We also found at least one [bug](https://github.com/Axelrod-Python/axelrod-fortran/issues/62).

Can you share more about your research interests? Your profile says game theory and AI. We've already trained and published strategies to win tournaments and may have other useful information.
